PIM-422 refactor into small methods
genny-project/messages pull request #52
Opened 2022-09-29 09:15 UTC by Trimikraj

2022-10-10 05:59 UTC, Expressionless commented
LGTM

2022-10-10 05:59 UTC, Expressionless approved these changes
LGTM

2022-10-10 23:08 UTC, varunshastry approved these changes

2022-10-12 03:57 UTC, varunshastry requested changes

2022-10-12 03:57 UTC, varunshastry commented on src/main/java/life/genny/messages/managers/QSendGridMessageManager.java
> +			System.out.println("Mail: " + mail);
s.o.p to be replaced with logger.

2022-10-19 01:19 UTC, Trimikraj commented on src/main/java/life/genny/messages/managers/QSendGridMessageManager.java
> +			System.out.println("Mail: " + mail);
done

2022-10-19 01:28 UTC, varunshastry approved these changes

2022-10-19 01:28 UTC, merged